/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsLlmProvidersRouteImport } from './routes/settings-llm-providers'
import { Route as SettingsGitProvidersRouteImport } from './routes/settings-git-providers'
import { Route as SettingsCodeReviewRouteImport } from './routes/settings-code-review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReviewsReviewRouteImport } from './routes/reviews.$reviewId'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const SettingsLlmProvidersRoute = SettingsLlmProvidersRouteImport.update({
  id: '/settings-llm-providers',
  path: '/settings-llm-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGitProvidersRoute = SettingsGitProvidersRouteImport.update({
  id: '/settings-git-providers',
  path: '/settings-git-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCodeReviewRoute = SettingsCodeReviewRouteImport.update({
  id: '/settings-code-review',
  path: '/settings-code-review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewRoute = ReviewsReviewRouteImport.update({
  id: '/reviews/$reviewId',
  path: '/reviews/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/reviews/$reviewId': typeof ReviewsReviewRoute
  '/settings': typeof SettingsRoute
  '/settings-code-review': typeof SettingsCodeReviewRoute
  '/settings-git-providers': typeof SettingsGitProvidersRoute
  '/settings-llm-providers': typeof SettingsLlmProvidersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/reviews/$reviewId': typeof ReviewsReviewRoute
  '/settings': typeof SettingsRoute
  '/settings-code-review': typeof SettingsCodeReviewRoute
  '/settings-git-providers': typeof SettingsGitProvidersRoute
  '/settings-llm-providers': typeof SettingsLlmProvidersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/reviews/$reviewId': typeof ReviewsReviewRoute
  '/settings': typeof SettingsRoute
  '/settings-code-review': typeof SettingsCodeReviewRoute
  '/settings-git-providers': typeof SettingsGitProvidersRoute
  '/settings-llm-providers': typeof SettingsLlmProvidersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reviews'
    | '/reviews/$reviewId'
    | '/settings'
    | '/settings-code-review'
    | '/settings-git-providers'
    | '/settings-llm-providers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reviews'
    | '/reviews/$reviewId'
    | '/settings'
    | '/settings-code-review'
    | '/settings-git-providers'
    | '/settings-llm-providers'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reviews'
    | '/reviews/$reviewId'
    | '/settings'
    | '/settings-code-review'
    | '/settings-git-providers'
    | '/settings-llm-providers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ReviewsRoute: typeof ReviewsRoute
  ReviewsReviewRoute: typeof ReviewsReviewRoute
  SettingsRoute: typeof SettingsRoute
  SettingsCodeReviewRoute: typeof SettingsCodeReviewRoute
  SettingsGitProvidersRoute: typeof SettingsGitProvidersRoute
  SettingsLlmProvidersRoute: typeof SettingsLlmProvidersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings-llm-providers': {
      id: '/settings-llm-providers'
      path: '/settings-llm-providers'
      fullPath: '/settings-llm-providers'
      preLoaderRoute: typeof SettingsLlmProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-git-providers': {
      id: '/settings-git-providers'
      path: '/settings-git-providers'
      fullPath: '/settings-git-providers'
      preLoaderRoute: typeof SettingsGitProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-code-review': {
      id: '/settings-code-review'
      path: '/settings-code-review'
      fullPath: '/settings-code-review'
      preLoaderRoute: typeof SettingsCodeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$reviewId': {
      id: '/reviews/$reviewId'
      path: '/reviews/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof ReviewsReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ReviewsRoute: ReviewsRoute,
  ReviewsReviewRoute: ReviewsReviewRoute,
  SettingsRoute: SettingsRoute,
  SettingsCodeReviewRoute: SettingsCodeReviewRoute,
  SettingsGitProvidersRoute: SettingsGitProvidersRoute,
  SettingsLlmProvidersRoute: SettingsLlmProvidersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
