import {describe, expect, test} from "bun:test"

import {Entity} from "../../../src/domain/entities/entity"
import {UniqueId} from "../../../src/domain/value-objects/unique-id.value-object"

interface IStubProps {
    label: string
    metadata: {
        attempts: number
    }
}

class StubEntity extends Entity<IStubProps> {
    public constructor(id: UniqueId | undefined, props: IStubProps) {
        super(id, props)
    }
}

class OtherStubEntity extends Entity<IStubProps> {
    public constructor(id: UniqueId | undefined, props: IStubProps) {
        super(id, props)
    }
}

describe("Entity", () => {
    test("creates entity with auto-generated uuid when id is omitted", () => {
        const entity = new StubEntity(undefined, {
            label: "autogenerated",
            metadata: {attempts: 1},
        })

        expect(entity.id.value).toMatch(
            /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
        )
    })

    test("uses provided unique id when passed", () => {
        const id = UniqueId.create("entity-1")
        const entity = new StubEntity(id, {
            label: "provided",
            metadata: {attempts: 1},
        })

        expect(entity.id.equals(id)).toBe(true)
    })

    test("isEqual returns true for same id and false for mismatch/null/undefined/other type", () => {
        const id = UniqueId.create("entity-1")
        const left = new StubEntity(id, {label: "left", metadata: {attempts: 1}})
        const right = new StubEntity(id, {label: "right", metadata: {attempts: 2}})
        const different = new StubEntity(UniqueId.create("entity-2"), {
            label: "different",
            metadata: {attempts: 3},
        })
        const otherType = new OtherStubEntity(id, {
            label: "other-type",
            metadata: {attempts: 4},
        })

        expect(left.isEqual(right)).toBe(true)
        expect(left.equals(right)).toBe(true)
        expect(left.isEqual(different)).toBe(false)
        expect(left.isEqual(null)).toBe(false)
        expect(left.isEqual(undefined)).toBe(false)
        expect(left.isEqual(otherType)).toBe(false)
    })

    test("freezes input props shallowly while keeping nested refs mutable", () => {
        const sourceProps: IStubProps = {
            label: "frozen",
            metadata: {attempts: 1},
        }
        void new StubEntity(UniqueId.create("entity-3"), sourceProps)

        expect(Object.isFrozen(sourceProps)).toBe(true)

        expect(() => {
            sourceProps.label = "changed"
        }).toThrow()

        sourceProps.metadata.attempts = 2
        expect(sourceProps.metadata.attempts).toBe(2)
    })
})
